This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./dp.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dp.acn....done (43 entries accepted, 0 rejected).
Sorting entries....done (370 comparisons).
Generating output file dp.acr....done (16 lines written, 0 warnings).
Output written in dp.acr.
Transcript written in dp.alg.
