This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./dp.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dp.acn....done (56 entries accepted, 0 rejected).
Sorting entries....done (356 comparisons).
Generating output file dp.acr....done (27 lines written, 0 warnings).
Output written in dp.acr.
Transcript written in dp.alg.
