This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./example_paper.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file example_paper.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file example_paper.acr....done (15 lines written, 0 warnings).
Output written in example_paper.acr.
Transcript written in example_paper.alg.
